name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'   # runs every hour
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          username: 'Bean-Pringles'
          stats-file: 'STATS.md'   # File where stats will be generated
          theme: 'radical'
          show_icons: true
          count_private: true       # Optional: include private contributions
          include_all_commits: true # Optional: include all commits

      - name: Commit stats
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add STATS.md
          git commit -m "Update GitHub stats" || echo "No changes"
          git push
